name: WASI Build

on: [push, pull_request]

jobs:
  wasi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          WASI_SDK=wasi-sdk-19.0
          WASI_SDK_URL=https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-19/wasi-sdk-19.0-linux.tar.gz
          if ! [ -d ${WASI_SDK} ]; then curl -L ${WASI_SDK_URL} | tar xzf -; fi

          mkdir -p build
          cat > build/Makefile.conf <<END
          export PATH := $(pwd)/${WASI_SDK}/bin:${PATH}
          WASI_SYSROOT := $(pwd)/${WASI_SDK}/share/wasi-sysroot

          CONFIG := wasi
          PREFIX := /

          ENABLE_TCL := 0
          ENABLE_READLINE := 0
          ENABLE_PLUGINS := 0
          ENABLE_ZLIB := 0
          END

          make -C build -f ../Makefile CXX=clang -j$(nproc)
